/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes to this file, as it will be overwritten.
// However, you can modify this file once it has been generated.

import { Route as rootRoute } from './routes/__root'
import { Route as DealsImport } from './routes/deals'
import { Route as CopilotImport } from './routes/copilot'
import { Route as IndexImport } from './routes/index'

const DealsRoute = DealsImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRoute,
} as any)

const CopilotRoute = CopilotImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/deals': typeof DealsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/deals': typeof DealsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/deals': typeof DealsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/copilot' | '/deals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/copilot' | '/deals'
  id: '__root__' | '/' | '/copilot' | '/deals'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopilotRoute: typeof CopilotRoute
  DealsRoute: typeof DealsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopilotRoute: CopilotRoute,
  DealsRoute: DealsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
