resources:
  apps:
    db_residential_copilot_app:
      name: "db-residential-copilot-${bundle.target}"
      description: "Databricks Residential Investment Copilot"
      source_code_path: ../src/app/.build
      resources:
        - name: "db"
          database:
            database_name: "databricks_postgres"
            instance_name: "db-residential-copilot"
            permission: "CAN_CONNECT_AND_CREATE"
